controllers:
    resource: ../src/Controller/
    type: attribute
app_entry:
  path: '/{req}'
  defaults: { _controller: App\Controller\EntryController::index }
  requirements:
    req: "^((?!api).)*$"